# Generated by Django 5.1.1 on 2024-09-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('A', 'Statue'), ('B', 'Tower')], default='A', help_text='Type of your structure', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(db_column='image', upload_to='images/posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title of your post', max_length=200, unique=True),
        ),
    ]
