# Generated by Django 5.1.1 on 2024-09-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_type_alter_post_image_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(db_column='image', help_text='Image of your post', upload_to='images/posts'),
        ),
    ]
