# Generated by Django 5.1.1 on 2024-09-10 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 19, 21, 16, 58314, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title of your post', max_length=200, unique=True, unique_for_date='pub_date'),
        ),
    ]
