# Generated by Django 5.1.1 on 2024-09-10 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_remove_post_type_alter_post_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 19, 45, 41, 523188, tzinfo=datetime.timezone.utc)),
        ),
    ]
