# Generated by Django 5.1.1 on 2024-09-11 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 11, 19, 5, 47, 57605, tzinfo=datetime.timezone.utc)),
        ),
    ]
